CHANGELOG.md
dev-requirements.txt
pyproject.toml
svdtools/patch.py

When using `_strip` in patches, it's not guaranteed that the `<displayName>` tag will be present. This resulted in an error for me when trying to patch a file.
While setting up and snooping around I also noticed that a couple of dev requirements were missing, and that the `home-page` URL in `pyproject.toml` was outdated.

Minor bugfixes, add `_strip_end`

---

README.md
svdtools/patch.py

SVD files allow multiple address blocks per peripheral.
This commit adds support for _add and _modify of peripherals with multiple addressblocks.
A new keyword (addressblocks) had to be introduced as YAML does not allow multiple config options with the same name. The addressblocks keyword supports a list of addressblocks.

Add support for multiple address blocks

---

.gitignore
.travis.yml
dev-requirements.txt
svdtools/__init__.py
svdtools/cli.py
svdtools/makedeps.py
svdtools/test/test_makedeps.py
tools/check_esp32.sh
tools/check_lpc55.sh
tools/check_stm32.sh

This is a straightforward port of [makedeps.py](https://github.com/stm32-rs/stm32-rs/blob/master/scripts/makedeps.py) but writing to the single output file instead of outputting many lines to stdout. By passing the output file path, it also knows what to put in the generated file without having to assume/be told you're using a ".deps" folder name.
For stm32-rs this allows updating the Makefile as:
```diff
diff --git a/Makefile b/Makefile
index 69be8d3..75b5ead 100644
--- a/Makefile
+++ b/Makefile
@@ -119,6 +119,6 @@ update-venv:
.deps/%.d: devices/%.yaml
@mkdir -p .deps
-       python3 scripts/makedeps.py $< > $@
+       svd makedeps $< $@
-include .deps/*
```
This was a quick port so I did it first to sort of test the waters. Is there interest in bringing this and similar tools from …

Add makedeps script

---

svdtools/__init__.py
svdtools/cli.py
svdtools/mmap.py
svdtools/test/test_mmap.py

This adds the `svdmmap.py` script from stm32-rs, which is used to generate a text-based memory map from an SVD which shows all peripherals, registers, fields, and interrupts, and is designed to be suitable for use with diff tools, to make it easier to see what the effect of a change in the SVD or a YAML file will do to the final device memory map.
At some point I'd like to make more automated tooling for generating these diffs, since for a given PR against a PAC, they allow you to quickly see which devices are affected at all (good for catching surprise changes to other devices!), what peripherals are affected in a given device, and precisely what the final changes are, in a compact text-based format.

Add mmap script

---

svdtools/patch.py

It turns out `fnmatch` is case-insensitive on Windows, causing some very rare build failures, e.g. https://github.com/stm32-rs/stm32-rs/pull/369. Using `fnmatchcase` should remedy the issue.

Use fnmatchcase for case sensitivity on all platforms

---

svdtools/patch.py

In a vendor-supplied SVD file, the following layout was encountered within a peripheral:
```xml
<registers>
<register>...</register>
<register>...</register>
<cluster>
<name>CHANNEL[%s]</name>
<description />
<register>...</register>
<register>...</register>
</cluster>
</registers>
```
The ability to modify the `<cluster>` tag's `description` attribute was needed, however this did not appear to be possible. This PR is just a quick and dirty method of accomplishing such. Patching can be performed by:
```yaml
DMAC:
_modify:
_cluster:
"CHANNEL*":
description: "Direct Memory Access Channels"
```
I've sort of repurposed `_cluster` here, but this shouldn't cause any problems (as far as I can tell) as it's being used in a new context. If there are any concerns with this approach, or any other …

Add the ability to modify clusters

---

README.md
svdtools/patch.py

Allows patterns in _strip/_stripend. This makes it easier to remove repetitive suffixes (like e.g. enable1 in register pin1)
The patterns use filename global syntax and match shortest prefix/postfix possible.

Allow patterns in _strip/_strip_end

---

README.md
svdtools/patch.py

Hello!
Over at [`avr-device`][avr-device] we've been happy users of svdpatch for quite some time (If you're wondering, we created a [tool][atdf2svd] to convert the AVR register descriptions to SVD).  We've accumulated a few changes to the patching script, which I have now forward-ported so they could be applied here, to hopefully be useful for other people as well.  In particular:
> Add a new patch directive which allows overwriting existing enumerated values.  Example:
>
> ```yaml
> ADC:
>   _modify:
>     ADCSRA:
>       access: read-write
>   ADCSRA:
>     ADPS:
>       _replace_enum:
>         PRESCALER_2: [1, "Prescaler Value 2"]
>         PRESCALER_4: [2, "Prescaler Value 4"]
>         PRESCALER_8: [3, "Prescaler Value 8"]
>         PRESCALER_16: [4, "Prescaler Value 16"]
> …
```

Changes from avr-device

---

.travis.yml
tools/check_esp8266.sh

The [esp-rs/esp8266](https://github.com/esp-rs/esp8266) repo is using `svdtools` as well, so I figured we may as well check against that too. ~~I also noticed that the *check_esp32* entry in `.travis.yml` was in both `include` and `allow_failures`, so I de-duplicated it.~~ (Turns out we need that for some reason :) )

Add a check for the esp8266

---

svdtools/patch.py

Currently most SVD files generated by `patch` are not SVD schema compliant, usually because the ordering of child elements is incorrect. For example, in SVD it's required that `dim`, `dimIncrement`, and `dimIndex`, if present in an element, are always first and in that order, which was always violated by `patch` before this PR.
This PR sorts SVDs into the correct order before outputting. It's still possible for a generated SVD to be invalid, for example if a patch generates multiple `writeConstraint` entries. Fixing that is left for a later PR as it's more likely to cause breaking changes in CI.

Update patch to generate schema-compliant SVD output

---

README.md
svdtools/patch.py

Previously `copy_peripheral` did not quite do what it promised; some interrupts from the template would be copied incorrectly and some interrupts already on the target would not be preserved though they should have been, but in a very chaotic way that was hard to predict. The recent change in https://github.com/stm32-rs/svdtools/pull/35 muddied the water further.
This PR fixes those bugs and better documents the expected behaviour. It fixes the regression in https://github.com/stm32-rs/stm32-rs/pull/440 and in fact makes the situation a little better, as many interrupts are now associated with the correct peripheral. This should be at least no worse than the 0.1.7 behaviour and fixes the change in 0.1.8, so I intend to release this ASAP.

Fix and document copy_peripheral behaviour

---

tools/check_lpc55.sh

Moved the repo into the `lpc55` organization, keeping up :)
Do you think it would make sense to build the PAC as well? For stm32 it's probably too much, but for lpc55 (on my relatively beefy machine...) a simple `cargo build` takes ~30 seconds, which seems acceptable?

Update lpc55-pac repository

---

tools/check_lpc55.sh

Apologies for the noise :)
We recently jumped ahead of the overdue svd2rust release, patching out some old lints but mainly [getting rid of bare-metal](https://github.com/lpc55/lpc55-pac/commit/7a033fbfb118f1177b8c7080a582dbab6604a5aa) (using interrupt::Nr from cortex-m instead), which led to a failure here. Added a dedicated [check target](https://github.com/lpc55/lpc55-pac/commit/1125223de278fb5db82ce640ab0e2bd6bb3d1ad9) now.
Answers https://github.com/stm32-rs/svdtools/pull/48#issuecomment-787467450.

Fix LPC55 check

---

.github/workflows/ci.yaml
Makefile
pyproject.toml
svdtools/interrupts.py
svdtools/mmap.py
svdtools/patch.py

lxml's ElementTree API preserves comments in the original XML, which allows us to preserve licensing comments often found in SVD files.
Adding a new dependency is a bit of a shame, but lxml is already widely used and available.

Swap to using lxml instead of stdlib xml

---

CHANGELOG.md
example/common_patches/tsc/tsc.yaml
svdtools/mmap.py
svdtools/patch.py

Need to test
Preferably using
https://github.com/rust-embedded/svd2rust/pull/503

field array collect

---

svdtools/patch.py

When splitting a field, the offset for the first bit of the field will be set to 0.
If the field start at an offset, that won't work nicely.
This pull request properly set the offset for each field, also allowing to split multiple fields in the same register.

Fix bitoffset for _split

---

README.md
svdtools/patch.py

This pull request allow to specify a custom name and description for `_split` with support for a placeholder to put the iterator value in the string.
Example:
```yaml
C1MR:
_split:
CHxFM: 
name: CH%sFM
description: Processor 1 transmit channel %s status set
CHxOM: 
name: CH%sOM
description: Processor 1 receive channel %s status clear
```

Custom name and description for _split

---

README.md
svdtools/patch.py

This pull request allow to specify a different name when merging fields, and allow to use a list of fspec to merge instead of just getting the common base name.
Example:
```yaml
_merge:
FIELD: [FIELD1, FIELD_?]
_merge:
FIELD:
- FIELD1
- FIELD_?
_merge:
NEW_FIELD: "FIELD*"
```

Support array of fspec and renaming for _merge

---

svdtools/patch.py

In #74 the behaviour for sorting fields when working out enumerated values changed to use the `bitOffset` attribute instead of sorting for natural numbers inside the name. This worked fine in our tests, but the RP2040 SVD uses `bitRange` for many of its fields, which therefore didn't have a `bitOffset`. We already have a `get_field_offset_width` method that does the right thing, so this PR swaps to using it. The RP2040 SVD now patches OK, and the stm32-rs SVDs are all identical after this change too.

Fix computing offset of fields that specify a bitRange instead

---

svdtools/patch.py

This turned out to be easier than I thought, especially since we already override this method for OrderedDicts. Unsurprisingly it's found a whole load of duplicate keys in stm32-rs though which I guess will need fixing before we can pass CI, heh.

Add detection of duplicate keys. Closes #63.

---

svdtools/patch.py

This should fix the issue in #83. There's not really any point us setting `displayName` to the same as `name`, so just remove it instead, but only do that if it's actually there.
@mgottschlag, would you mind checking this does what you expect on rp2040-pac? I've run it on your branch and it does patch without any errors and the diff looks ok, but I'd appreciate if you could confirm it is doing what you wanted.
cc https://github.com/rp-rs/rp2040-pac/pull/41

Remove displayName from derived registers when it exists. Fixes #83

---

CHANGELOG-python.md
pyproject.toml

Changelog: <https://github.com/yaml/pyyaml/releases/tag/6.0>
PyYAML released version 6, and the only breaking change is "always require `Loader` arg to `yaml.load()`", which would have resulted in a deprecation warning with version 5.
Supporting both 5 and 6 makes this easier for people to use during the transition phase because PyYAML is often provided as an OS package on Linux distributions.

Add support for PyYAML v6

---

.github/workflows/ci.yaml
.github/workflows/release.yml
.github/workflows/rust-ci.yaml
CHANGELOG-rust.md
Cargo.toml
src/cli.rs
src/convert/convert_cli.rs
src/patch/mod.rs
src/patch/register.rs

Closes #110 for rust svdtools version
Require https://github.com/stm32-rs/stm32-rs/pull/734

enum usage + expand_properties

---

src/cli.rs

The Rust-based svdtools patch help output suggests that the user provides an SVD file:
```
$ svdtools patch --help
svdtools-patch
Patches an SVD file as specified by a YAML file
USAGE:
svdtools patch <SVD_FILE>
ARGS:
<SVD_FILE>    Path to input SVD file
OPTIONS:
-h, --help    Print help information
```
If we actually provide an SVD file, the tool errors.
Compare this with the Python documentation, which suggests that the user
provides a YAML file, not an SVD file.
```
$ svd patch --help
Usage: svd patch [OPTIONS] YAML_FILE
Patches an SVD file as specified by a YAML file
Options:
--help  Show this message and exit.
```

Accept a YAML file, not an SVD file, when patching

---

src/patch/device.rs
src/patch/peripheral.rs
src/patch/register.rs
svdtools/patch.py

improve derive for registers (breaking)

---

CHANGELOG-python.md
CHANGELOG-rust.md
src/patch/peripheral.rs
src/patch/register.rs
svdtools/patch.py

This is breaking change.
But this let reuse patches for registers with and without prefixes.

move _strips before _modify

---

svdtools/patch.py

Fixes this error message:
```
File "/home/jan/.local/lib/python3.7/site-packages/svdtools/patch.py", line 855, in derive_register
description = rmod.get(description, None)
UnboundLocalError: local variable 'description' referenced before assignment
```

Fix UnboundLocalError in patch.py

---

src/patch/mod.rs

Add derivedFrom to register maker (rust version only)

---

src/html/html_cli.rs
src/html/template.html
src/patch/mod.rs
src/patch/peripheral.rs

Support for register write constraint
```yaml
ERTC:
_modify:
WP:
size: 8
writeConstraint: [0, 0xFF]
```
```xml
<register>
<name>WP</name>
<displayName>WP</displayName>
<description>write protection register</description>
<addressOffset>0x24</addressOffset>
<size>0x8</size>
<access>write-only</access>
<resetValue>0x00000000</resetValue>
<writeConstraint>
<range>
<minimum>0</minimum>
<maximum>255</maximum>
</range>
</writeConstraint>
</register>
```
Also disable 'Field toggle' for no field register in html

Write constraint register

---

CHANGELOG-rust.md
src/patch/peripheral.rs

workaround for `svdconv` M366 error

use register size as dimIncrement for 1-element arrays

---

src/html/index.template.html
src/html/template.html

Just happened to notice this 😅 For the index I've just removed the `stm32-rs` text altogether, and in the device template I've used the device's name instead.

Remove/replace occurrences of "stm32-rs" in the HTML templates

---

CHANGELOG-rust.md
example/common_patches/tsc/tsc.yaml
example/incomplete-stm32l4x2.yaml
src/html/html_cli.rs
src/patch/mod.rs
src/patch/peripheral.rs
src/patch/register.rs

collect in cluster/array descriptions

---

CHANGELOG-rust.md
src/cli.rs
src/patch/device.rs
src/patch/mod.rs
src/patch/peripheral.rs
src/patch/register.rs

Do not change default behavior, but add option flag.
With `--enum derive field` this fixes most of `svdconv` M206 errors. Although I can't guarantee this doesn't break anything.

derive fields instead of enums

---

src/html/htmlcompare_cli.rs
src/html/index.template.html
src/html/template.html

This pull request proposes some improvement to the HTML templates:
- Fix `<style>` being used outside of `<head>` in `htmlcompare`
- Use `<details>` elements and drop JavaScript (JQuery+Bootstrap JS)
- Some CSS fixes to remove unwanted elements overlap.
Thank you for this awesome project!

html: multiple template fixes

---

src/html/template.html

When no hash is present in the URL, `locationHashChanged` JavaScript function will add an extra `#` symbol at the end of the URL. This is problematic as it adds another entry in the browser history, making it impossible to go back to previous page using the browser 'back button'.
Sorry for introducing this bug in https://github.com/rust-embedded/svdtools/pull/198.

html/template.html: fix location hash redirect

---

CHANGELOG-python.md
CHANGELOG-rust.md
Cargo.toml
README.md
src/patch/register.rs
svdtools/patch.py

For example:
```yaml
"A?B?ENR,A?BENR":
"*EN":
_name: Enable
Disabled: [0, "The selected clock is disabled"]
Enabled: [1, "The selected clock is enabled"]
```
gives us:

specify `name` for `enumeratedValues`

---

src/html/template.html

Commits https://github.com/rust-embedded/svdtools/commit/2efd6b4d1c75f80fafab190b22cfe2ccecba0cd1 and https://github.com/rust-embedded/svdtools/commit/0b644d655216fc57ade26e5e8ad70c01e65fc42b change nothing in the rendered result, they are just some code improvement.
Commit https://github.com/rust-embedded/svdtools/commit/e9490a58e63fc2bb3358a21dd30264d267fb34d0 causes green links to be a bit more readable (but still green) using built-in Bootstrap "success" color.
Feel free to cherry-pick the commits you want to include from this pull request :-)
I was going to propose an upgrade to Bootstrap 5 to get some modern nice to have (such as smooth scrolling by default and dark theme), but:
- there is no glyphicons built-in (the alternative would be SVG icons)
- it means less browser …

html/template.html: code improvements

---

CHANGELOG-rust.md
src/patch/peripheral.rs

~~Depends on #216~~
Blocked by ~~https://github.com/stm32-rs/stm32-rs/pull/968 https://github.com/stm32-rs/stm32-rs/pull/969~~

process cluster rule simplify

---

CHANGELOG-rust.md
src/patch/mod.rs

With 0.13.3, some descriptions were removed from rp2040.svd:
```
--- a/svd/rp2040.svd.patched
+++ b/svd/rp2040.svd.patched
@@ -14513,23 +14513,18 @@
<fields>
<field>
<name>STABLE</name>
-              <description>Oscillator is running and stable</description>
<bitOffset>31</bitOffset>
<bitWidth>1</bitWidth>
<access>read-only</access>
</field>
<field>
<name>DIV_RUNNING</name>
-              <description>post-divider is running
- this resets to 0 but transitions to 1 during chip startup</description>
<bitOffset>16</bitOffset>
<bitWidth>1</bitWidth>
<access>read-only</access>
</field>
<field>
<name>ENABLED</name>
-              <description>Oscillator is enabled but not necessarily running and stable
- this resets to 0 but transitions to 1 during chip startup</description> …
```

Let opt_interpolate return the plain string if path is None

---

res/add_register/patch.yaml
src/patch/mod.rs

This updates `make_field()` to honor a writeConstraint field, the same way that `make_register()` does.
I included a new unit test that verifies the behavior.

Support defining write constraints for newly created fields

---

README.md
res/expand_cluster/expected.svd
res/expand_cluster/mspm0g350x.svd
res/expand_cluster/patch.yml
src/patch/peripheral.rs
src/patch/yaml_ext.rs

Implemented _expand_cluster, and added an example.
It takes a string or an array of strings as arguments.
Added an example in /res/expand_cluster and updated the readme
closes: https://github.com/rust-embedded/svdtools/issues/246

Expand cluster implementation + fix  _strip to work on clusters

---

src/patch/mod.rs

This change provides a mechanism to patch svd files without depending on file system paths.
fixes #265

patch: allow processing without path dependencies

---

.github/workflows/rust-ci.yaml
Cargo.toml
src/convert/convert_cli.rs
src/convert/mod.rs
src/html/mod.rs
src/interrupts/mod.rs
src/lib.rs
src/makedeps/mod.rs
src/mmap/mod.rs
src/patch/mod.rs
tests/example1.rs

This is made by adding a "bin" feature that's enabled by default, inspired by what was done in https://github.com/rust-embedded/svd2rust/pull/619.
Additionally, support for JSON and YAML configs has also been made optional but default. This includes what should be the only behavior change: if neither were enabled at build-time, passing a config file is an error.
The motivation came from https://github.com/Rahix/avr-device/issues/201, but this should be a generally beneficial change for everybody.
Since some of the features of the CLI aren't very useful when using svdtools as a library, they just vanish without the "bin" feature. This is for two reasons: one is to reduce diff size, and two is to avoid having to refactor all capabilities to have a library equivalent. There is little …

Make CLI optional (for library usage)
