- CHANGELOG.md
- svdtools/patch.py
Mirroring capability of peripherals for registers.
> Add strip functionality to registers for bitfields

- .travis.yml
- Makefile
- README.md
- tools/check_lpc55.sh
@MabezDev care for a quick review?
I think it makes sense to check whether `svd2rust` can handle the output, but it does slow down CI a lot...
> Add Travis badge. Add check for LPC55

- .travis.yml
- bors.toml
This PR enables [bors](https://bors.tech) for svdtools.
As configured, everyone with push access (me and @nickray) can approve PRs, but I'm very happy to add anyone else interested -- @jessebraham @MabezDev?
> Enable bors

- svdtools/patch.py
Currently you cannot add or change interrupts on derived peripherals, since they're not included when processing peripherals to avoid trying to process registers where they don't exist. However, many derived peripherals still need or have interrupts, so this PR allows working with them.
> Process changes to interrupts on derived peripherals

- svdtools/patch.py
Use this method in collect_in_cluster so that dimIndex is correctly identified in the case that there are comma-separated substrings
> Add version of iter_registers that returns the matched substring

- README.md
> Update README to include note about On/Off values

- pyproject.toml
- svdtools/patch.py
See https://pypi.org/project/braceexpand/ and https://stackoverflow.com/questions/22996645/brace-expansion-in-python-glob
> support for sequences inside braces in namespecs

- .github/workflows/ci.yaml
- CHANGELOG-rust.md
- src/patch/device.rs
- src/patch/mod.rs
- src/patch/peripheral.rs
- svdtools/patch.py
> cluster add/modify (rust)

- src/patch/peripheral.rs
> iter registers always 1-depth

- svdtools/patch.py
Hello,
This is essentially the same content as in pull request #132 but without formatting changes.
No changes to required Python version compared to original code base.
```
"PERIPHERAL_*":
_modify:
"REG_*1":
addressOffset: 8
_clusters:
CLU_*:
_modify:
REG_2:
addressOffset: 0
CLU_2:
_modify:
REG_1:
name: my_REG_1
```
```
"PERIPHERAL_*":
_add:
"REG_COMMON_NEW":
addressOffset: 8
_clusters:
CLU_*:
_add:
REG_NEW:
addressOffset: 8
_add:
"CLU_3":
addressOffset: 300
"REG_1":
addressOffset: 0
"REG_2":
addressOffset: 4
```
```
"PERIPHERAL_*":
_delete:
- "REG_*1"
_clusters:
"CLU_*":
_delete:
- "REG_*1"
```
```
"PERIPHERAL_*":
_strip:
- "REG_*"
_clusters:
"CLU_*":
_strip:
- "R*"
"CLU_1":
_strip_end:
- "1"
```
Best regards,
RHamalainen
> Extend support for clusters (Python only)

- CHANGELOG-rust.md
- src/patch/register.rs
for better compatibility with CMSIS specification
related to https://github.com/stm32-rs/stm32-rs/issues/825
> add field name in enumeratedValues derive path

- CHANGELOG-rust.md
- Cargo.toml
- src/cli.rs
- src/convert/convert_cli.rs
- src/lib.rs
- src/patch/mod.rs
- src/patch/patch_cli.rs
- tests/example1.rs
> encode config for patch

- CHANGELOG-rust.md
- src/patch/mod.rs
- src/patch/peripheral.rs
- src/patch/register.rs
- svdtools/patch.py
> allow , in spec_ind

- .github/workflows/ci.yaml
- CHANGELOG-python.md
- CHANGELOG-rust.md
- README.md
- src/patch/mod.rs
- svdtools/patch.py
cc @Emilgardis 
python based `stm32-rs` CI is disabled as we plan to deprecate it.
> default enum value

- CHANGELOG-rust.md
- src/patch/peripheral.rs
> use all_registers in clear_fields

- CHANGELOG-rust.md
- src/cli.rs
- src/patch/mod.rs
> post patch validate

- CHANGELOG-rust.md
- Cargo.toml
- src/patch/mod.rs
cc @Logiase @Emilgardis 
closes #189
> escape on match

- CHANGELOG-rust.md
- src/patch/mod.rs
- src/patch/peripheral.rs
> cluster of arrays

- CHANGELOG-rust.md
- src/patch/device.rs
- src/patch/mod.rs
- src/patch/peripheral.rs
- src/patch/register.rs
- src/patch/yaml_ext.rs
~~Blocked by https://github.com/stm32-rs/stm32-rs/pull/967~~
> Ext::KEYWORDS

- CHANGELOG-rust.md
- src/patch/mod.rs
- src/patch/peripheral.rs
- src/patch/register.rs
~~Depends on #217~~
This is less powerful, but simpler version of #196.
> Interpolate path and name

- CHANGELOG-rust.md
- src/patch/mod.rs
Missed in #216 
cc @Emilgardis
> allow underscore in spec

- CHANGELOG-rust.md
- Cargo.toml
- src/patch/mod.rs
- src/patch/peripheral.rs
- src/patch/yaml_ext.rs
Better YAML parsing errors (including duplicate map keys)
> yaml_rust -> yaml_rust2

- src/patch/mod.rs
> Fix cluster _modify

- CHANGELOG-rust.md
- src/html/html_cli.rs
Fixes https://github.com/stm32-rs/stm32-rs/actions/runs/11816709665/job/32920572930
> Support derived registers/fields in "svdtools html"

- CHANGELOG-rust.md
- Cargo.toml
- src/patch/device.rs
- src/patch/mod.rs
- src/patch/peripheral.rs
by address offset instead of adding in the end
cc @Emilgardis
> Calculate _add position for peripherals and registers

- svdtools/patch.py
While having a look to fix an issue in the tool I will try to provide some small patches that I think slightly improve the python code.
Let me know if this is desired or not.
Thank you
> svdtools/patch: Refactor entry code

- src/patch/register.rs
- src/patch/yaml_ext.rs
> Allow Yaml as key for GetVal (internal)
